from .encode import (
	ENCODER_IN_CHANNELS,
	ENCODER_EXPAND_CHANNELS,
	ENCODER_INTERMEDIATE_CHANNELS,
	ENCODER_OUT_CHANNELS,
)

from .decode import (
	DECODER_MAX_PARENTS,
	DECODER_ACTIVATION_THRESHOLD,
	DECODER_TOP_K_EXTRACT,
	DECODER_INTERACT_RANKS,
	DECODER_PRESERVE_RANKS,
	DECODER_INTERMEDIATE_CHANNELS,
	DECODER_HIDDEN_CHANNELS,
	DECODER_OUT_CHANNELS,
)

from .encoder_layer import (
	ENCODER_STACK_DEPTH,
	ENCODER_INTER_STACK_CHANNELS,
	ENCODER_STACK_OUT_CHANNELS,
)

from .fc import (
	FC_DEFAULT_ACTIVATION,
)

__all__ = [
	# Encoder node
	"ENCODER_IN_CHANNELS",
	"ENCODER_EXPAND_CHANNELS",
	"ENCODER_INTERMEDIATE_CHANNELS",
	"ENCODER_OUT_CHANNELS",
	# Decoder node
	"DECODER_MAX_PARENTS",
	"DECODER_ACTIVATION_THRESHOLD",
	"DECODER_TOP_K_EXTRACT",
	"DECODER_INTERACT_RANKS",
	"DECODER_PRESERVE_RANKS",
	"DECODER_INTERMEDIATE_CHANNELS",
	"DECODER_HIDDEN_CHANNELS",
	"DECODER_OUT_CHANNELS",
	# EncoderLayer
	"ENCODER_STACK_DEPTH",
	"ENCODER_INTER_STACK_CHANNELS",
	"ENCODER_STACK_OUT_CHANNELS",
	# FCLayer
	"FC_DEFAULT_ACTIVATION",
]

